version: 2.1.{build}
configuration: Release
branches:
  only:
  - master
platform: x86
environment:
  hockeyapp_app_id:
    secure: sjmGaxHV6PWeZD20m+0CN62zoKHxlRALtSI5PE4xugNi5siO2YYMO87OVKJMO2p1
  hockeyapp_api_token:
    secure: US7d2cLw+jBRv5DIeqalgSOw2HP7NwKTttU/HfjhTKdm2umyOtj1MQayNFOfd978
before_build:
- ps: .\appveyor\build\InstallSQLite.ps1
after_build:
- ps : .\appveyor\build\CreateSymbolZipFiles.ps1
build:
  parallel: true
  verbosity: minimal
artifacts:
- path: src\wallabag\AppPackages\wallabag_{version}.0_Test\wallabag_{version}.0_x86_x64_arm.appxbundle
  name: "wallabag Store package"
- path: hockeyapp-symbols\symbols-ARM.zip
  name: "Symbol files (ARM)"
- path: hockeyapp-symbols\symbols-x86.zip
  name: "Symbol files (x86)"
- path: hockeyapp-symbols\symbols-x64.zip
  name: "Symbol files (x64)"